### ISSUE TITLE
sni可以是选填吗？

### ISSUE THREAD

**Issue by JAakkOoops** [llc1123/trojan-rust#3]
sni可以是选填吗？因为有时候不只一台前置主机，如果可以设置多个sni就更好了

**Comment by llc1123** [comment]
目前不支持，如果将来支持也只会允许证书中的域名

**Comment by JAakkOoops** [comment]
好的 感谢回复，因为我个人使用的是泛域，迫切需要，祝trojan-rust做大做强

**Comment by llc1123** [comment]
已进入master分支
