### ISSUE TITLE
性能表现不佳

### ISSUE THREAD

**Issue by reizhi** [llc1123/trojan-rust#6]
这只是一个反馈不算是 issue 。
在某些存在 QoS 的网络环境下，trojan-rust 的速度表现明显低于 trojan-gfw 和 trojan-go。
使用同一个测速点反复测试，trojan-rust 只能达到 230Mbps 左右，trojan-gfw 和 trojan-go 均能达到 450Mbps 以上。

**Comment by llc1123** [comment]
无法复现，请提供更详细的信息

**Comment by llc1123** [comment]
把话说明白啊，关了是什么意思

**Comment by reizhi** [comment]
你觉得你的实现没问题，我可以用其他人的 trojan 分支。
所用网络是澳门 CTM ，that's all I want to share.

**Comment by llc1123** [comment]
那我只能认为这是一条无效的反馈，你丢下一句话就跑，问你要详细情况你也拒绝提供，不管是谁都没办法解决。既然你觉得你没有问题，那你爱用啥用啥关我屁事
